#ifndef _BOARD_CONFIG_H_
#define _BOARD_CONFIG_H_

// Vobot Global configuration

#include <driver/gpio.h>

#define AUDIO_INPUT_SAMPLE_RATE  24000
#define AUDIO_OUTPUT_SAMPLE_RATE 24000

#define AUDIO_I2S_GPIO_MCLK GPIO_NUM_42
#define AUDIO_I2S_GPIO_WS GPIO_NUM_41
#define AUDIO_I2S_GPIO_BCLK GPIO_NUM_40
#define AUDIO_I2S_GPIO_DIN  GPIO_NUM_21
#define AUDIO_I2S_GPIO_DOUT GPIO_NUM_39

#define AUDIO_CODEC_PA_PIN       GPIO_NUM_15
#define AUDIO_CODEC_I2C_SDA_PIN  GPIO_NUM_1
#define AUDIO_CODEC_I2C_SCL_PIN  GPIO_NUM_2
#define AUDIO_CODEC_ES8311_ADDR  ES8311_CODEC_DEFAULT_ADDR

#define BOOT_BUTTON_GPIO        GPIO_NUM_7
#define VOLUME_UP_BUTTON_GPIO   GPIO_NUM_0
#define VOLUME_DOWN_BUTTON_GPIO GPIO_NUM_6
#define POWER_BUTTON_GPIO       GPIO_NUM_48

#define DISPLAY_WIDTH   128
#define DISPLAY_HEIGHT  160
#define DISPLAY_MIRROR_X false
#define DISPLAY_MIRROR_Y false
#define DISPLAY_SWAP_XY false

#define DISPLAY_OFFSET_X  2
#define DISPLAY_OFFSET_Y  1

#define DISPLAY_BACKLIGHT_PIN GPIO_NUM_13
#define DISPLAY_BACKLIGHT_OUTPUT_INVERT false

#define DISPLAY_SDA GPIO_NUM_11
#define DISPLAY_SCL GPIO_NUM_12
#define DISPLAY_DC GPIO_NUM_9
#define DISPLAY_CS GPIO_NUM_10
#define DISPLAY_RES GPIO_NUM_14

#define DISPLAY_SPI_SCLK_HZ     (40 * 1000 * 1000)

#define BATTARY_MEASURE_PIN GPIO_NUM_4
#define CTRL_SYSTEM_POWER_PIN GPIO_NUM_47

#endif // _BOARD_CONFIG_H_
